# Generated by Django 5.0.6 on 2024-07-04 06:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_ckeditorportafolio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CkEditorPortafolio',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
    ]
